# Generated by Django 4.1.7 on 2023-05-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
